language: android
android:
    components:
        # Uncomment the lines below if you want to
        # use the latest revision of Android SDK Tools
        - tools
        - platform-tools

        # The BuildTools version used by your project
        - build-tools-28.0.3

        # The SDK version used to compile your project
        - android-28

        # Additional components
        - extra-android-support
        - extra-android-m2repository
        #- extra-google-google_play_services
        #- extra-google-m2repository
        #- extra-android-m2repository
        #- addon-google_apis-google-26
        # A gente n usa nada disso ainda

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-28

    licenses:
        - '.+'
    script:
        - chmod +x ./gradlew